SELECT 
  CODIGO_PONTO,
  DATA_PONTO,
  TO_CHAR(HORA_ENTRADA, 'HH24:MI') AS HORA_ENTRADA,
  TO_CHAR(HORA_SAIDA, 'HH24:MI') AS HORA_SAIDA,
  CODIGO_FUNCIONARIO
FROM 
  LABDATABASE.PONTOS
ORDER BY
  CODIGO_FUNCIONARIO, DATA_PONTO