/*Apaga os relacionamentos*/
ALTER TABLE PEDIDOS DROP CONSTRAINT FORNECEDORES_PEDIDOS_FK;
ALTER TABLE PEDIDOS DROP CONSTRAINT CLIENTES_PEDIDOS_FK;
ALTER TABLE ITENS_PEDIDO DROP CONSTRAINT PEDIDOS_ITENS_PEDIDO_FK;
ALTER TABLE ITENS_PEDIDO DROP CONSTRAINT PRODUTOS_ITENS_PEDIDO_FK;

/*Apaga as tabelas*/
DROP TABLE FORNECEDORES;
DROP TABLE CLIENTES;
DROP TABLE PEDIDOS;
DROP TABLE PRODUTOS;
DROP TABLE ITENS_PEDIDO;

/*Apaga as sequences*/
DROP SEQUENCE PEDIDOS_CODIGO_PEDIDO_SEQ;
DROP SEQUENCE ITENS_PEDIDO_CODIGO_ITEM_SEQ;
DROP SEQUENCE PRODUTOS_CODIGO_PRODUTO_SEQ;

/*Cria as tabelas*/
CREATE TABLE FORNECEDORES (
                CNPJ VARCHAR2(14) NOT NULL,
                RAZAO_SOCIAL VARCHAR2(255) NOT NULL,
                NOME_FANTASIA VARCHAR2(255) NOT NULL,
                CONSTRAINT FORNECEDORES_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE CLIENTES (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT CLIENTES_PK PRIMARY KEY (CPF)
);

CREATE TABLE PEDIDOS (
                CODIGO_PEDIDO NUMBER NOT NULL,
                DATA_PEDIDO DATE NOT NULL,
                CPF VARCHAR2(11) NOT NULL,
                CNPJ VARCHAR2(14) NOT NULL,
                CONSTRAINT PEDIDOS_PK PRIMARY KEY (CODIGO_PEDIDO)
);

CREATE TABLE PRODUTOS (
                CODIGO_PRODUTO NUMBER NOT NULL,
                DESCRICAO_PRODUTO VARCHAR2(255) NOT NULL,
                CONSTRAINT PRODUTOS_PK PRIMARY KEY (CODIGO_PRODUTO)
);

CREATE TABLE ITENS_PEDIDO (
                CODIGO_ITEM_PEDIDO NUMBER NOT NULL,
                QUANTIDADE NUMBER(9,3) NOT NULL,
                VALOR_UNITARIO NUMBER(9,2) NOT NULL,
                CODIGO_PEDIDO NUMBER NOT NULL,
                CODIGO_PRODUTO NUMBER NOT NULL,
                CONSTRAINT ITENS_PEDIDO_PK PRIMARY KEY (CODIGO_ITEM_PEDIDO)
);

/*Cria as sequences*/
CREATE SEQUENCE PEDIDOS_CODIGO_PEDIDO_SEQ;
CREATE SEQUENCE PRODUTOS_CODIGO_PRODUTO_SEQ;
CREATE SEQUENCE ITENS_PEDIDO_CODIGO_ITEM_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE PEDIDOS ADD CONSTRAINT FORNECEDORES_PEDIDOS_FK
FOREIGN KEY (CNPJ)
REFERENCES FORNECEDORES (CNPJ)
NOT DEFERRABLE;

ALTER TABLE PEDIDOS ADD CONSTRAINT CLIENTES_PEDIDOS_FK
FOREIGN KEY (CPF)
REFERENCES CLIENTES (CPF)
NOT DEFERRABLE;

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT PEDIDOS_ITENS_PEDIDO_FK
FOREIGN KEY (CODIGO_PEDIDO)
REFERENCES PEDIDOS (CODIGO_PEDIDO)
NOT DEFERRABLE;

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT PRODUTOS_ITENS_PEDIDO_FK
FOREIGN KEY (CODIGO_PRODUTO)
REFERENCES PRODUTOS (CODIGO_PRODUTO)
NOT DEFERRABLE;