
CREATE DATABASE sistema_biblioteca;
USE sistema_biblioteca;

CREATE TABLE Leitor (
    ID_LEITOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(15) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE Livro (
    ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(30) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    EDITORA VARCHAR(30) NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    QUANTIDADE INT DEFAULT 1
);

CREATE TABLE Emprestimo (
    ID_EMRPESTIMO INT PRIMARY KEY AUTO_INCREMENT,
    ID_LEITOR INT NOT NULL,
    ID_LIVRO INT NOT NULL, 
    DATA_EMPRESTIMO DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    DATA_DEV_REALIZAFA DATE NOT NULL,
    VALOR_MULTA DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (id_livro) REFERENCES Livro(id_livro),
    FOREIGN KEY (id_leitor) REFERENCES Leitor(id_leitor)
)