/*DROP REFERENCES*/
ALTER TABLE LABDATABASE.PACIENTE
DROP CONSTRAINT LABDATABASE.ID_PROF_FK;

/*DROP INDEXES*/
DROP INDEX LABDATABASE.PACIENTE_IDX;
DROP INDEX LABDATABASE.INFOS_PROFISSIONAIS_IDX;

/*DROP TABLES*/
DROP TABLE LABDATABASE.PACIENTE;
DROP TABLE LABDATABASE.INFOS_PROFISSIONAIS;

/*DROP VIEWS*/
DROP VIEW LABDATABASE.PACIENTE_PESO;
DROP VIEW LABDATABASE.PACIENTE_PROFISSIONAIS;

/*DROP SEQUENCES*/
DROP SEQUENCE LABDATABASE.PACIENTE_SEQ;
DROP SEQUENCE LABDATABASE.INFOS_PROFISSIONAIS_SEQ;

/*CREATE TABLE*/
CREATE TABLE LABDATABASE.PACIENTE (
    CPF VARCHAR2(11) NOT NULL,
    NOME_PACIENTE VARCHAR2(100) NOT NULL,
    IDADE NUMERIC NOT NULL,
    TAMANHO_ABDOMINAL NUMERIC NOT NULL,
    ALTURA NUMERIC NOT NULL,
    PESO NUMERIC NOT NULL,
    CONSTRAINT PACIENTE_ID_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.INFOS_PROFISSIONAIS (
    NOME_PROFISSIONAL VARCHAR2(100) NOT NULL,
    ESPECIALIDADE VARCHAR2(100) NOT NULL,
   	PROF_LICENCA NUMERIC NOT NULL,
    CONTATO_ENVIO VARCHAR2(100) NOT NULL,
    CONSTRAINT ID_PROF_PK PRIMARY KEY (PROF_LICENCA)
);

CREATE TABLE LABDATABASE.PROFISSIONAIS_RESPONSAVEIS (
    PROF_LICENCA NUMERIC NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    CONSTRAINT ID_RESPONSAVEL_PK PRIMARY KEY (PROF_LICENCA)
);

/*ADD CONSTRAINT FOREIGN KEY*/
ALTER TABLE LABDATABASE.INFOS_PROFISSIONAIS ADD CONSTRAINT LICENCA_FK
FOREIGN KEY (PROF_LICENCA)
REFERENCES LABDATABASE.PACIENTE (PROF_LICENCA)
NOT DEFERRABLE;

/*GRANT ACCESS*/
GRANT ALL ON LABDATABASE.PACIENTES TO LABDATABASE;
GRANT ALL ON LABDATABASE.AGENDAMENTOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;

commit;
