/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.PONTOS DROP CONSTRAINT FUNCIONARIOS_PONTOS_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.FUNCIONARIOS;
DROP TABLE LABDATABASE.PONTOS;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.PONTOS_CODIGO_PONTO_SEQ;
DROP SEQUENCE LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.FUNCIONARIOS (
                CODIGO_FUNCIONARIO NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CARGO VARCHAR2(255) NOT NULL,
                CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY (CODIGO_FUNCIONARIO)
);

CREATE TABLE LABDATABASE.PONTOS (
                CODIGO_PONTO NUMBER NOT NULL,
                DATA_PONTO DATE NOT NULL,
                HORA_ENTRADA DATE NOT NULL,
                HORA_SAIDA DATE NOT NULL,
                CODIGO_FUNCIONARIO NUMBER NOT NULL,
                CONSTRAINT PONTOS_PK PRIMARY KEY (CODIGO_PONTO)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.PONTOS_CODIGO_PONTO_SEQ;
CREATE SEQUENCE LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.PONTOS ADD CONSTRAINT FUNCIONARIOS_PONTOS_FK
FOREIGN KEY (CODIGO_FUNCIONARIO)
REFERENCES LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.FUNCIONARIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.PONTOS TO LABDATABASE;