INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'João Silva', 'Analista de Sistemas');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Maria Souza', 'Desenvolvedora Front-End');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Carlos Pereira', 'Gerente de Projetos');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Ana Oliveira', 'DevOps Engineer');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Lucas Martins', 'Desenvolvedor Backend');

INSERT INTO LABDATABASE.FUNCIONARIOS (CODIGO_FUNCIONARIO, NOME, CARGO)
VALUES (LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIO_SEQ.NEXTVAL, 'Fernanda Lima', 'Analista de Qualidade');
