DECLARE
  VCOD_PONTO NUMBER;
BEGIN
  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('08:30', 'HH24:MI'), TO_DATE('16:30', 'HH24:MI'), 1);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('07:00', 'HH24:MI'), TO_DATE('15:00', 'HH24:MI'), 1);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('07:30', 'HH24:MI'), TO_DATE('15:30', 'HH24:MI'), 1);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('08:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'), 2);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('07:00', 'HH24:MI'), TO_DATE('15:00', 'HH24:MI'), 2);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('08:30', 'HH24:MI'), TO_DATE('16:30', 'HH24:MI'), 2);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('08:15', 'HH24:MI'), TO_DATE('17:00', 'HH24:MI'), 3);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('07:45', 'HH24:MI'), TO_DATE('16:15', 'HH24:MI'), 3);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('09:00', 'HH24:MI'), TO_DATE('17:30', 'HH24:MI'), 3);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('09:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'), 4);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('08:00', 'HH24:MI'), TO_DATE('17:00', 'HH24:MI'), 4);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('07:30', 'HH24:MI'), TO_DATE('16:30', 'HH24:MI'), 4);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('08:00', 'HH24:MI'), TO_DATE('17:00', 'HH24:MI'), 5);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('07:30', 'HH24:MI'), TO_DATE('16:30', 'HH24:MI'), 5);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('09:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'), 5);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('08:15', 'HH24:MI'), TO_DATE('17:45', 'HH24:MI'), 6);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-02', 'YYYY-MM-DD'), TO_DATE('08:30', 'HH24:MI'), TO_DATE('17:00', 'HH24:MI'), 6);

  VCOD_PONTO := LABDATABASE.PONTOS_CODIGO_PONTO_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.PONTOS (CODIGO_PONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, CODIGO_FUNCIONARIO)
  VALUES (VCOD_PONTO, TO_DATE('2024-10-03', 'YYYY-MM-DD'), TO_DATE('08:45', 'HH24:MI'), TO_DATE('17:15', 'HH24:MI'), 6);

  COMMIT;
END;
