/*INSERE DADOS NA TABELA DE PRODUTOS*/
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE XR');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE XS');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE 11');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE 12');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE 13');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'IPHONE 14');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'SAMGUNG GALAXY S20');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'SAMGUNG GALAXY S21');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'SAMGUNG GALAXY S22');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'SAMGUNG GALAXY S23');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'MOTOROLA G50');
INSERT INTO PRODUTOS VALUES(PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL, 'MOTOROLA G55');

/*INSERE DADOS NA TABELA DE CLIENTES*/
INSERT INTO CLIENTES VALUES('01234567891', 'JOÃO GABRIEL');
INSERT INTO CLIENTES VALUES('20123456789', 'JOÃO GUILHERME');
INSERT INTO CLIENTES VALUES('32012345678', 'JOÃO JOSÉ');
INSERT INTO CLIENTES VALUES('43201234567', 'JOSÉ ANTÔNIO');
INSERT INTO CLIENTES VALUES('54320123456', 'JOSÉ CARLOS');
INSERT INTO CLIENTES VALUES('65432012345', 'ANTÔNIO CARLOS');
INSERT INTO CLIENTES VALUES('76543201234', 'CARLOS ANTÔNIO');
INSERT INTO CLIENTES VALUES('87654320123', 'MARCO ANTÔNIO');

/*INSERE DADOS NA TABELA DE FORNECEDORES*/
INSERT INTO FORNECEDORES VALUES('01234567891234', 'ALIADOS DO BRASIL SA', 'ALIADOS');
INSERT INTO FORNECEDORES VALUES('00123456789123', 'COLEGAS UNIDOS SA', 'COLEGAS');
INSERT INTO FORNECEDORES VALUES('00012345678912', 'AMIGOS DOS AMIGOS SA', 'AMIGOS DOS AMIGOS');
INSERT INTO FORNECEDORES VALUES('00001234567891', 'DELEGANDO SA', 'DELEGANDO');

/*INSERE DADOS NA TABELA DE PEDIDOS E ITENS*/
DECLARE
  VCOD_PEDIDO NUMBER;
  VCOD_ITEM_PEDIDO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_PEDIDO := PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL;
  
  INSERT INTO PEDIDOS VALUES(VCOD_PEDIDO,    /*CODIGO_PEDIDO*/
                             SYSDATE,        /*DATA_PEDIDO*/
                             '43201234567',  /*CPF*/
                             '01234567891234'/*CNPJ*/
                             );
  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'IPHONE 11';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  111,              /*QUANTIDADE*/
                                  3900,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
END;

DECLARE
  VCOD_PEDIDO NUMBER;
  VCOD_ITEM_PEDIDO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_PEDIDO := PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL;
  
  INSERT INTO PEDIDOS VALUES(VCOD_PEDIDO,    /*CODIGO_PEDIDO*/
                             SYSDATE,        /*DATA_PEDIDO*/
                             '01234567891',  /*CPF*/
                             '01234567891234'/*CNPJ*/
                             );
  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'IPHONE 12';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  122,              /*QUANTIDADE*/
                                  4500,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
END;

DECLARE
  VCOD_PEDIDO NUMBER;
  VCOD_ITEM_PEDIDO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_PEDIDO := PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL;
  
  INSERT INTO PEDIDOS VALUES(VCOD_PEDIDO,    /*CODIGO_PEDIDO*/
                             SYSDATE,        /*DATA_PEDIDO*/
                             '87654320123',  /*CPF*/
                             '01234567891234'/*CNPJ*/
                             );
  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'IPHONE 13';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  131,              /*QUANTIDADE*/
                                  6500,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
                                  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'SAMGUNG GALAXY S22';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  100,              /*QUANTIDADE*/
                                  5500,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
END;

DECLARE
  VCOD_PEDIDO NUMBER;
  VCOD_ITEM_PEDIDO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_PEDIDO := PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL;
  
  INSERT INTO PEDIDOS VALUES(VCOD_PEDIDO,    /*CODIGO_PEDIDO*/
                             SYSDATE,        /*DATA_PEDIDO*/
                             '32012345678',  /*CPF*/
                             '00001234567891'/*CNPJ*/
                             );
  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'IPHONE 11';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  111,              /*QUANTIDADE*/
                                  3750,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
                                  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'MOTOROLA G50';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  78,              /*QUANTIDADE*/
                                  2900,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
                                  
END;

DECLARE
  VCOD_PEDIDO NUMBER;
  VCOD_ITEM_PEDIDO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_PEDIDO := PRODUTOS_CODIGO_PRODUTO_SEQ.NEXTVAL;
  
  INSERT INTO PEDIDOS VALUES(VCOD_PEDIDO,    /*CODIGO_PEDIDO*/
                             SYSDATE,        /*DATA_PEDIDO*/
                             '76543201234',  /*CPF*/
                             '00012345678912'/*CNPJ*/
                             );
  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'IPHONE 14';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  50,              /*QUANTIDADE*/
                                  8000,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
                                  
  VCOD_ITEM_PEDIDO := ITENS_PEDIDO_CODIGO_ITEM_SEQ.NEXTVAL;
  
  SELECT CODIGO_PRODUTO
    INTO VCOD_PRODUTO
    FROM PRODUTOS
   WHERE DESCRICAO_PRODUTO = 'MOTOROLA G50';
  
  INSERT INTO ITENS_PEDIDO VALUES(VCOD_ITEM_PEDIDO, /*CODIGO_ITEM_PEDIDO*/
                                  30,              /*QUANTIDADE*/
                                  2900,             /*VALOR*/
                                  VCOD_PEDIDO,      /*CODIGO_PEDIDO*/
                                  VCOD_PRODUTO      /*CODIGO_PRODUTO*/
                                  );
                                  
END;

/*Confirma(persiste) as alterações*/
COMMIT;